---
version: 2.1

executors:
  ansible-lint:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/ansible-lint:latest
    resource_class: small
  molecule:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
  yamllint:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/yamllint:latest
    resource_class: small
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/trailing-whitespace:latest
    resource_class: small

jobs:
  ansible-lint:
    executor: ansible-lint
    steps:
      - checkout
      - run:
          name: Install the role
          command: |
            ansible-galaxy install git+${CIRCLE_REPOSITORY_URL},${CIRCLE_SHA1}
      - run:
          name: Install dependent roles
          command: |
            for d in `find molecule/* -maxdepth 1`; do
              if [[ $d =~ molecule/.*/requirements.yml ]]; then
                ansible-galaxy install -r $d
              fi
            done
      - run:
          name: Execulte Ansible-lint
          command: ansible-lint
      - run:
          name: Show Ansible-lint version
          command: |
            pip list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
            ansible-lint --version
  molecule:
    executor: molecule
    parameters:
      checkout-path:
        type: string
      molecule-image:
        type: string
    steps:
      - checkout:
          path: << parameters.checkout-path >>
      - run:
          name: Install Molecule and dependencies
          command: |
            cd << parameters.checkout-path >>
            pip3 install -r molecule/requirements.txt
      - run:
          name: Test with Molecule
          command: |
            cd << parameters.checkout-path >>
            molecule test
          environment:
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
            MOLECULE_IMAGE: << parameters.molecule-image >>
      - run:
          name: Show Ansible version
          command: |
            pip3 list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
      - run:
          name: Show Molecule version
          command: molecule --version
  yamllint:
    executor: yamllint
    steps:
      - checkout
      - run:
          name: Execute yamllint
          command: yamllint *
      - run:
          name: Show yamllint version
          command: |
            yamllint --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule:
          matrix:
            parameters:
              checkout-path:
                - 'mariadb_create_db'
              molecule-image:
                - 'ghcr.io/docker-hub-tm/ansible-test/centos7:latest'
                - 'ghcr.io/docker-hub-tm/ansible-test/centos-stream8:latest'
          requires:
            - ansible-lint
